version: '3'
services:
  account-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      - POSTGRES_DB=account
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=curkepro00.
    ports:
      - 5432:5432
